print("Normal:")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()
print("With fewer print() invocations:")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print()
print("Larger by 2:")
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("*****      ******")
print("    *      *")
print("    *      *")
print("    *      *")
print("    *      *")
print("    ********")
print()
print("Duplicated:")
print("        *         " * 2)
print("       * *        " * 2)
print("      *   *       " * 2)
print("     *     *      " * 2)
print("    *       *     " * 2)
print("   *         *    " * 2)
print("  *           *   " * 2)
print(" *             *  " * 2)
print("*****      ****** " * 2)
print("    *      *      " * 2)
print("    *      *      " * 2)
print("    *      *      " * 2)
print("    *      *      " * 2)
print("    ********      " * 2)
